-- Users, agents, login lockout and refresh tokens (PR 1), plus the
-- idempotency records that housekeeping cleans up.

CREATE TABLE agent_users (
  id             BIGSERIAL PRIMARY KEY,
  username       TEXT NOT NULL UNIQUE,
  password_hash  TEXT NOT NULL,              -- argon2id PHC string
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  disabled_at    TIMESTAMPTZ
);

CREATE TABLE agent_login_failures (         -- lockout window per (username, client IP)
  username   TEXT NOT NULL,
  client_ip  INET NOT NULL,
  failed_at  TIMESTAMPTZ NOT NULL
);
CREATE INDEX agent_login_failures_lookup ON agent_login_failures (username, client_ip, failed_at);
CREATE INDEX agent_login_failures_failed_at ON agent_login_failures (failed_at);   -- housekeeping

CREATE TABLE agent_agents (
  id               UUID PRIMARY KEY,          -- agent_id, generated by the agent
  user_id          BIGINT NOT NULL REFERENCES agent_users(id),
  hostname         TEXT,
  os               TEXT,
  arch             TEXT,
  last_version     TEXT,
  first_seen_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE agent_refresh_tokens (
  id             BIGSERIAL PRIMARY KEY,
  token_hash     BYTEA NOT NULL UNIQUE,       -- sha256(token); raw tokens are never stored
  family_id      UUID NOT NULL,
  parent_id      BIGINT REFERENCES agent_refresh_tokens(id) ON DELETE SET NULL,  -- the token this one replaced
  user_id        BIGINT NOT NULL REFERENCES agent_users(id),
  agent_id       UUID NOT NULL REFERENCES agent_agents(id),
  issued_at      TIMESTAMPTZ NOT NULL,
  expires_at     TIMESTAMPTZ NOT NULL,
  rotated_at     TIMESTAMPTZ,                 -- set when exchanged for a new one
  grace_used_at  TIMESTAMPTZ,                 -- set when replayed within the grace window
  revoked_at     TIMESTAMPTZ,
  revoked_reason TEXT                         -- 'grace' | 'reuse' | 'logout' | 'disabled'
);
CREATE INDEX agent_refresh_tokens_family ON agent_refresh_tokens (family_id);
CREATE INDEX agent_refresh_tokens_parent ON agent_refresh_tokens (parent_id);
CREATE INDEX agent_refresh_tokens_user ON agent_refresh_tokens (user_id);
CREATE INDEX agent_refresh_tokens_expires_at ON agent_refresh_tokens (expires_at);  -- housekeeping

CREATE TABLE agent_idempotency_keys (
  user_id         BIGINT NOT NULL REFERENCES agent_users(id),
  key             TEXT NOT NULL,
  request_sha256  BYTEA NOT NULL,
  status_code     INTEGER NOT NULL,
  response_body   BYTEA NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, key)
);
CREATE INDEX agent_idempotency_keys_created_at ON agent_idempotency_keys (created_at);  -- housekeeping
