/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestRouteImport } from './routes/request'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as OauthGlinkRouteImport } from './routes/oauth/glink'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGlinkRoute = OauthGlinkRouteImport.update({
  id: '/oauth/glink',
  path: '/oauth/glink',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/request': typeof RequestRoute
  '/requests': typeof RequestsRoute
  '/oauth/glink': typeof OauthGlinkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/request': typeof RequestRoute
  '/requests': typeof RequestsRoute
  '/oauth/glink': typeof OauthGlinkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/request': typeof RequestRoute
  '/requests': typeof RequestsRoute
  '/oauth/glink': typeof OauthGlinkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/request' | '/requests' | '/oauth/glink'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/request' | '/requests' | '/oauth/glink'
  id: '__root__' | '/' | '/request' | '/requests' | '/oauth/glink'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RequestRoute: typeof RequestRoute
  RequestsRoute: typeof RequestsRoute
  OauthGlinkRoute: typeof OauthGlinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/glink': {
      id: '/oauth/glink'
      path: '/oauth/glink'
      fullPath: '/oauth/glink'
      preLoaderRoute: typeof OauthGlinkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RequestRoute: RequestRoute,
  RequestsRoute: RequestsRoute,
  OauthGlinkRoute: OauthGlinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
