/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DuplicatesRouteImport } from './routes/duplicates'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManageDataRouteImport } from './routes/manage-data'
import { Route as RequestRouteImport } from './routes/request'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OauthGlinkRouteImport } from './routes/oauth/glink'
import { Route as ScansScanIdRouteImport } from './routes/scans.$scanId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDataRoute = ManageDataRouteImport.update({
  id: '/manage-data',
  path: '/manage-data',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGlinkRoute = OauthGlinkRouteImport.update({
  id: '/oauth/glink',
  path: '/oauth/glink',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansScanIdRoute = ScansScanIdRouteImport.update({
  id: '/scans/$scanId',
  path: '/scans/$scanId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/duplicates': typeof DuplicatesRoute
  '/login': typeof LoginRoute
  '/manage-data': typeof ManageDataRoute
  '/request': typeof RequestRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/oauth/glink': typeof OauthGlinkRoute
  '/scans/$scanId': typeof ScansScanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/duplicates': typeof DuplicatesRoute
  '/login': typeof LoginRoute
  '/manage-data': typeof ManageDataRoute
  '/request': typeof RequestRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/oauth/glink': typeof OauthGlinkRoute
  '/scans/$scanId': typeof ScansScanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/duplicates': typeof DuplicatesRoute
  '/login': typeof LoginRoute
  '/manage-data': typeof ManageDataRoute
  '/request': typeof RequestRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/oauth/glink': typeof OauthGlinkRoute
  '/scans/$scanId': typeof ScansScanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/duplicates'
    | '/login'
    | '/manage-data'
    | '/request'
    | '/requests'
    | '/settings'
    | '/oauth/glink'
    | '/scans/$scanId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/duplicates'
    | '/login'
    | '/manage-data'
    | '/request'
    | '/requests'
    | '/settings'
    | '/oauth/glink'
    | '/scans/$scanId'
  id:
    | '__root__'
    | '/'
    | '/duplicates'
    | '/login'
    | '/manage-data'
    | '/request'
    | '/requests'
    | '/settings'
    | '/oauth/glink'
    | '/scans/$scanId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DuplicatesRoute: typeof DuplicatesRoute
  LoginRoute: typeof LoginRoute
  ManageDataRoute: typeof ManageDataRoute
  RequestRoute: typeof RequestRoute
  RequestsRoute: typeof RequestsRoute
  SettingsRoute: typeof SettingsRoute
  OauthGlinkRoute: typeof OauthGlinkRoute
  ScansScanIdRoute: typeof ScansScanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-data': {
      id: '/manage-data'
      path: '/manage-data'
      fullPath: '/manage-data'
      preLoaderRoute: typeof ManageDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/glink': {
      id: '/oauth/glink'
      path: '/oauth/glink'
      fullPath: '/oauth/glink'
      preLoaderRoute: typeof OauthGlinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/$scanId': {
      id: '/scans/$scanId'
      path: '/scans/$scanId'
      fullPath: '/scans/$scanId'
      preLoaderRoute: typeof ScansScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DuplicatesRoute: DuplicatesRoute,
  LoginRoute: LoginRoute,
  ManageDataRoute: ManageDataRoute,
  RequestRoute: RequestRoute,
  RequestsRoute: RequestsRoute,
  SettingsRoute: SettingsRoute,
  OauthGlinkRoute: OauthGlinkRoute,
  ScansScanIdRoute: ScansScanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
