name: Docker UI Image CI

on:
  push:
    branches: ["main"]
    paths:
      - "ui/**"
  pull_request:
    branches: ["main"]
    paths:
      - "ui/**"

jobs:
  ui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}-ui" >>${GITHUB_ENV}

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image to Dockerhub
        with:
          image: ${{ env.REPO }}
          addLatest: true
          registry: docker.io
          dockerfile: ./ui/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
